### ISSUE TITLE
Code review

### ISSUE THREAD

**Issue by freekmurze** [laravel-notification-channels/evernote#2]
@mpociot you're on fire 🔥 👨 🔥 

😄 

Let me know when you're done with this one, then I'll go over it.

**Comment by freekmurze** [comment]
I've refactored some things in the `EvernoteChannel` to make it more readable. The tests seem to confirm that the code still works after the refactor.

Boo for Evernote not having tagged a release! I've changed `composer.json` so that a specific commit is being used.

**Comment by mpociot** [comment]
Thanks for the review!
